# Generated by Django 4.2.2 on 2023-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="picture_url",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
