# Generated by Django 4.2.2 on 2023-06-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_location_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="picture_url",
            field=models.TextField(null=True),
        ),
    ]
